### 1. Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "test@vaultx.com",
  "authKey": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
  "authSalt": "testsalt123",
  "kdfSalt": "kdfSalt123",
  "kdfParams": { "memory": 65536, "iterations": 3, "parallelism": 1 },
  "vaultKeyEnc": "encryptedvaultkey123",
  "vaultKeyIv": "vaultiv123"
}

### 2. Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test@vaultx.com",
  "authKey": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"
}

### 3. Refresh
POST http://localhost:5000/api/auth/refresh

### 4. Logout  (paste accessToken from login response)
POST http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNDIzNTk2MS04ODJiLTRiNWUtYmIzMS0wYjRjMTFkMjU5OTEiLCJzZXNzaW9uSWQiOiI5YzhiMTRlMS0wMTQyLTQyY2YtODMzMy01YmZlZTE1MjJiOGYiLCJpYXQiOjE3NzkwMTU3NTksImV4cCI6MTc3OTAxNjY1OX0.sYEFnVb56iRg-oe9ES6qc_SoaXhHsyRPVcOCvM4UICA



### Test Rate Limit — send login 6 times with wrong password
### 6th should return 429 Too Many Requests

### MultipleReqesting
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test@vaultx.com",
  "authKey": "wrongkey000000000000000000000000000000000000000000000000000000000000"
}